<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Emp.aspx.cs" Inherits="QuestionFive.Emp" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" DataKeyNames="empid">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="empid" HeaderText="empid" SortExpression="empid" InsertVisible="False" ReadOnly="True" Visible="False" />
                <asp:BoundField DataField="DeptId" HeaderText="Department ID" SortExpression="DeptId" />
                <asp:BoundField DataField="DeptName" HeaderText="DeptName" SortExpression="DeptName" Visible="False" />
                <asp:BoundField DataField="EmpName" HeaderText="Employee Name" SortExpression="EmpName" />
                <asp:BoundField DataField="Salary" HeaderText="Salary" SortExpression="Salary" Visible="False" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:QuestionsDBConnectionString %>" DeleteCommand="DELETE FROM [employees] WHERE [empid] = @empid" InsertCommand="INSERT INTO [employees] ([DeptId], [DeptName], [EmpName], [Salary]) VALUES (@DeptId, @DeptName, @EmpName, @Salary)" SelectCommand="SELECT * FROM [employees]" UpdateCommand="UPDATE [employees] SET [DeptId] = @DeptId, [DeptName] = @DeptName, [EmpName] = @EmpName, [Salary] = @Salary WHERE [empid] = @empid">
            <DeleteParameters>
                <asp:Parameter Name="empid" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="DeptId" Type="String" />
                <asp:Parameter Name="DeptName" Type="String" />
                <asp:Parameter Name="EmpName" Type="String" />
                <asp:Parameter Name="Salary" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="DeptId" Type="String" />
                <asp:Parameter Name="DeptName" Type="String" />
                <asp:Parameter Name="EmpName" Type="String" />
                <asp:Parameter Name="Salary" Type="String" />
                <asp:Parameter Name="empid" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <%--<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:QuestionsDBConnectionString %>" SelectCommand="SELECT [DeptName], [EmpName] FROM [employees]" ></asp:SqlDataSource>--%>
    
    </div>
    </form>
</body>
</html>
