<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EmpDetails.aspx.cs" Inherits="QuestionSix.EmpDetails" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            text-decoration: underline;
            color: #003366;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div class="auto-style1">
    
        <strong>Table Shows Department ID and Employee Names<br />
        <br />
        <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateRows="False" DataKeyNames="empid" DataSourceID="SqlDataSource1" Height="50px" Width="125px">
            <Fields>
                <asp:BoundField DataField="empid" HeaderText="empid" InsertVisible="False" ReadOnly="True" SortExpression="empid" />
                <asp:BoundField DataField="DeptId" HeaderText="DeptId" SortExpression="DeptId" />
                <asp:BoundField DataField="DeptName" HeaderText="DeptName" SortExpression="DeptName" />
                <asp:BoundField DataField="EmpName" HeaderText="EmpName" SortExpression="EmpName" />
                <asp:BoundField DataField="Salary" HeaderText="Salary" SortExpression="Salary" />
            </Fields>
        </asp:DetailsView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:QuestionsDBConnectionString %>" DeleteCommand="DELETE FROM [employees] WHERE [empid] = @empid" InsertCommand="INSERT INTO [employees] ([DeptId], [DeptName], [EmpName], [Salary]) VALUES (@DeptId, @DeptName, @EmpName, @Salary)" SelectCommand="SELECT * FROM [employees]" UpdateCommand="UPDATE [employees] SET [DeptId] = @DeptId, [DeptName] = @DeptName, [EmpName] = @EmpName, [Salary] = @Salary WHERE [empid] = @empid">
            <DeleteParameters>
                <asp:Parameter Name="empid" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="DeptId" Type="String" />
                <asp:Parameter Name="DeptName" Type="String" />
                <asp:Parameter Name="EmpName" Type="String" />
                <asp:Parameter Name="Salary" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="DeptId" Type="String" />
                <asp:Parameter Name="DeptName" Type="String" />
                <asp:Parameter Name="EmpName" Type="String" />
                <asp:Parameter Name="Salary" Type="String" />
                <asp:Parameter Name="empid" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        </strong>
    
    </div>
    </form>
</body>
</html>
