<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EmpDetails.aspx.cs" Inherits="QuestionSix.EmpDetails" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            color: #003366;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div class="auto-style1">
    
        <table align="center" style="width: 55%; bottom: -2147483648px; right: 45%; top: -10px; left: -45%; position: relative; float: right; height: 172px;">
            <tr>
                <td>&nbsp;</td>
                <td><strong>
                    <asp:DetailsView ID="DetailsView1" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateRows="False" CellPadding="4" DataKeyNames="empid" DataSourceID="SqlDataSource1" Font-Names="Arial" FooterText="by Elijah Ayeeta" ForeColor="#333333" GridLines="None" HeaderText="Detail View Shows Department ID and Eployee Names" Height="50px" Width="450px">
                        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                        <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
                        <EditRowStyle BackColor="#999999" />
                        <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
                        <Fields>
                            <asp:BoundField DataField="empid" HeaderText="empid" InsertVisible="False" ReadOnly="True" SortExpression="empid" Visible="False" />
                            <asp:BoundField DataField="DeptId" HeaderText="Department ID" SortExpression="DeptId">
                            <FooterStyle Font-Names="Corbel" />
                            </asp:BoundField>
                            <asp:BoundField DataField="DeptName" HeaderText="DeptName" SortExpression="DeptName" Visible="False" />
                            <asp:BoundField DataField="EmpName" HeaderText="Employee Name" SortExpression="EmpName" />
                            <asp:BoundField DataField="Salary" HeaderText="Salary" SortExpression="Salary" Visible="False" />
                        </Fields>
                        <FooterStyle BackColor="#5D7B9D" BorderColor="#336699" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    </asp:DetailsView>
                    </strong></td>
                <td>&nbsp;</td>
            </tr>
        </table>
        <strong>
        <br />
        <br />
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:QuestionsDBConnectionString %>" DeleteCommand="DELETE FROM [employees] WHERE [empid] = @empid" InsertCommand="INSERT INTO [employees] ([DeptId], [DeptName], [EmpName], [Salary]) VALUES (@DeptId, @DeptName, @EmpName, @Salary)" SelectCommand="SELECT * FROM [employees]" UpdateCommand="UPDATE [employees] SET [DeptId] = @DeptId, [DeptName] = @DeptName, [EmpName] = @EmpName, [Salary] = @Salary WHERE [empid] = @empid">
            <DeleteParameters>
                <asp:Parameter Name="empid" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="DeptId" Type="String" />
                <asp:Parameter Name="DeptName" Type="String" />
                <asp:Parameter Name="EmpName" Type="String" />
                <asp:Parameter Name="Salary" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="DeptId" Type="String" />
                <asp:Parameter Name="DeptName" Type="String" />
                <asp:Parameter Name="EmpName" Type="String" />
                <asp:Parameter Name="Salary" Type="String" />
                <asp:Parameter Name="empid" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        </strong>
    
    </div>
    </form>
</body>
</html>
