<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EmpDetails.aspx.cs" Inherits="QuestionFour.EmpDetails" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            text-align: center;
        }
        .auto-style2 {
            text-align: left;
            width: 348px;
        }
        .auto-style3 {
            width: 392px;
        }
    </style>
</head>
<body style="height: 426px">
    <form id="form1" runat="server">
    <div>
    
        <table style="width: 37%;">
            <tr>
                <td class="auto-style1" colspan="2">Employee Details</td>
            </tr>
            <tr>
                <td class="auto-style2">Employee Name</td>
                <td class="auto-style3">
                    <asp:TextBox ID="txtEmpName" runat="server" Width="293px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">Employee Dept.</td>
                <td class="auto-style3">
                    <asp:TextBox ID="txtEmpDep" runat="server" Width="291px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">Employee Salary</td>
                <td class="auto-style3">
                    <asp:TextBox ID="txtEmpSalary" runat="server" Width="291px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style2">
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:QuestionsDBConnectionString %>" SelectCommand="SELECT * FROM [emps]" DeleteCommand="Delete from [emps] where [empid] = @empid"></asp:SqlDataSource>
                </td>
                <td class="auto-style3">
                    <asp:Button ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnSubmit" runat="server" Text="Submit" OnClick="btnSubmit_Click" />
                </td>
            </tr>
        </table>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="empid" DataSourceID="SqlDataSource2">
            <Columns>
                <asp:BoundField DataField="empid" HeaderText="empid" InsertVisible="False" ReadOnly="True" SortExpression="empid" />
                <asp:BoundField DataField="empname" HeaderText="empname" SortExpression="empname" />
                <asp:BoundField DataField="empdep" HeaderText="empdep" SortExpression="empdep" />
                <asp:BoundField DataField="empsal" HeaderText="empsal" SortExpression="empsal" />
            </Columns>
        </asp:GridView>
    
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:QuestionsDBConnectionString %>" SelectCommand="SELECT * FROM [emps]"></asp:SqlDataSource>
    
    </div>
    </form>
</body>
</html>
